# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('par', models.IntegerField(default=72)),
                ('yards', models.IntegerField(blank=True, null=True)),
                ('slope', models.IntegerField(blank=True, null=True)),
                ('par1', models.IntegerField(default=4)),
                ('par2', models.IntegerField(default=4)),
                ('par3', models.IntegerField(default=4)),
                ('par4', models.IntegerField(default=4)),
                ('par5', models.IntegerField(default=4)),
                ('par6', models.IntegerField(default=4)),
                ('par7', models.IntegerField(default=4)),
                ('par8', models.IntegerField(default=4)),
                ('par9', models.IntegerField(default=4)),
                ('par10', models.IntegerField(default=4)),
                ('par11', models.IntegerField(default=4)),
                ('par12', models.IntegerField(default=4)),
                ('par13', models.IntegerField(default=4)),
                ('par14', models.IntegerField(default=4)),
                ('par15', models.IntegerField(default=4)),
                ('par16', models.IntegerField(default=4)),
                ('par17', models.IntegerField(default=4)),
                ('par18', models.IntegerField(default=4)),
                ('par_out', models.IntegerField(default=36)),
                ('par_in', models.IntegerField(default=36)),
                ('yards1', models.IntegerField(blank=True, null=True)),
                ('yards2', models.IntegerField(blank=True, null=True)),
                ('yards3', models.IntegerField(blank=True, null=True)),
                ('yards4', models.IntegerField(blank=True, null=True)),
                ('yards5', models.IntegerField(blank=True, null=True)),
                ('yards6', models.IntegerField(blank=True, null=True)),
                ('yards7', models.IntegerField(blank=True, null=True)),
                ('yards8', models.IntegerField(blank=True, null=True)),
                ('yards9', models.IntegerField(blank=True, null=True)),
                ('yards10', models.IntegerField(blank=True, null=True)),
                ('yards11', models.IntegerField(blank=True, null=True)),
                ('yards12', models.IntegerField(blank=True, null=True)),
                ('yards13', models.IntegerField(blank=True, null=True)),
                ('yards14', models.IntegerField(blank=True, null=True)),
                ('yards15', models.IntegerField(blank=True, null=True)),
                ('yards16', models.IntegerField(blank=True, null=True)),
                ('yards17', models.IntegerField(blank=True, null=True)),
                ('yards18', models.IntegerField(blank=True, null=True)),
                ('yards_out', models.IntegerField(blank=True, null=True)),
                ('yards_in', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoleInOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.IntegerField(blank=True, null=True)),
                ('yards', models.IntegerField(blank=True, null=True)),
                ('club', models.CharField(max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Course')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Golfer')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par1', models.IntegerField(default=4)),
                ('par2', models.IntegerField(default=4)),
                ('par3', models.IntegerField(default=4)),
                ('par4', models.IntegerField(default=4)),
                ('par5', models.IntegerField(default=4)),
                ('par6', models.IntegerField(default=4)),
                ('par7', models.IntegerField(default=4)),
                ('par8', models.IntegerField(default=4)),
                ('par9', models.IntegerField(default=4)),
                ('par10', models.IntegerField(default=4)),
                ('par11', models.IntegerField(default=4)),
                ('par12', models.IntegerField(default=4)),
                ('par13', models.IntegerField(default=4)),
                ('par14', models.IntegerField(default=4)),
                ('par15', models.IntegerField(default=4)),
                ('par16', models.IntegerField(default=4)),
                ('par17', models.IntegerField(default=4)),
                ('par18', models.IntegerField(default=4)),
                ('par_out', models.IntegerField(default=0)),
                ('par_in', models.IntegerField(default=0)),
                ('par', models.IntegerField(default=0)),
                ('play_date', models.DateField(verbose_name='date published')),
                ('hcap', models.CharField(default='N', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Course')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Golfer')),
            ],
        ),
        migrations.AddField(
            model_name='champs',
            name='golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Golfer'),
        ),
    ]
