# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duffers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleInOnex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.IntegerField(blank=True, null=True)),
                ('yards', models.IntegerField(blank=True, null=True)),
                ('club', models.CharField(max_length=20, null=True)),
                ('play_date', models.DateField(null=True, verbose_name='date published')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Course')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Golfer')),
            ],
        ),
        migrations.AddField(
            model_name='holeinone',
            name='play_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
