# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duffers', '0002_auto_20170502_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='handicap',
            field=models.IntegerField(default=0),
        ),
    ]
