# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duffers', '0003_golfer_handicap'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolferStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par3_avg', models.FloatField(default=0)),
                ('par4_avg', models.FloatField(default=0)),
                ('par5_avg', models.FloatField(default=0)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duffers.Golfer')),
            ],
        ),
        migrations.RemoveField(
            model_name='holeinonex',
            name='course',
        ),
        migrations.RemoveField(
            model_name='holeinonex',
            name='golfer',
        ),
        migrations.DeleteModel(
            name='HoleInOnex',
        ),
    ]
