# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duffers', '0004_auto_20170507_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='par',
        ),
        migrations.RemoveField(
            model_name='course',
            name='par_in',
        ),
        migrations.RemoveField(
            model_name='course',
            name='par_out',
        ),
        migrations.RemoveField(
            model_name='course',
            name='yards',
        ),
        migrations.RemoveField(
            model_name='course',
            name='yards_in',
        ),
        migrations.RemoveField(
            model_name='course',
            name='yards_out',
        ),
        migrations.RemoveField(
            model_name='score',
            name='par',
        ),
        migrations.RemoveField(
            model_name='score',
            name='par_in',
        ),
        migrations.RemoveField(
            model_name='score',
            name='par_out',
        ),
    ]
