# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duffers', '0005_auto_20170507_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='par',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='course',
            name='par_in',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='course',
            name='par_out',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='course',
            name='yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='yards_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='yards_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='par',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='par_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='par_out',
            field=models.IntegerField(default=0),
        ),
    ]
